### ISSUE TITLE
Investigate: Invalid Image URL in wallet setting makes invitations not work

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#613]
Creating an invitation when the Image URL for the wallet is not valid seems to cause issues with the invitation.

For example if I have just a blank string in image url
![image.png](https://images.zenhubusercontent.com/5f74f6bfc45ba1b7a96e77cc/8654485c-f19b-409f-a292-ff4312160649)

Then go create an invitation, it does seem to create the invite link
```
https://traction-acapy-dev.apps.silver.devops.gov.bc.ca?c_i=eyJAdHlwZSI6ICJodHRwczovL2RpZGNvbW0ub3JnL2Nvbm5lY3Rpb25zLzEuMC9pbnZpdGF0aW9uIiwgIkBpZCI6ICIxM2ZmNTI3MS1lZjY2LTQyOTEtOTU2OS00OTU2Y2FjNGI2ZjUiLCAicmVjaXBpZW50S2V5cyI6IFsiOXQ0TGM0ejVkVjN3TGRIRDJ4Wmt5cGNDOEp4TWN6MXcyQkZOVTFKUnhodUEiXSwgImltYWdlVXJsIjogIiIsICJzZXJ2aWNlRW5kcG9pbnQiOiAiaHR0cHM6Ly90cmFjdGlvbi1hY2FweS1kZXYuYXBwcy5zaWx2ZXIuZGV2b3BzLmdvdi5iYy5jYSIsICJsYWJlbCI6ICJMdWNhcyBEZXYgMiJ9
```
And a QR code.

However, scanning that QR code with the BC Wallet then results in an "Invalid QR Code. Please Try Again" message in the wallet:
![image.png](https://images.zenhubusercontent.com/5f74f6bfc45ba1b7a96e77cc/a12d4c9f-4301-4e52-8579-9ea0b9f1362a)

If you then try and regenerate the invitation link you can see this in acapy and it fails
```
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 420, in setup_context
return await task
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
future.result()
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 180, in _step
result = coro.send(None)
File "/home/indy/traction_plugins/traction_innkeeper/v1_0/connections/routes.py", line 38, in connections_invitation
invitation = await connection.retrieve_invitation(session)
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/connections/models/conn_record.py", line 442, in retrieve_invitation
).deserialize(ser)
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/messaging/agent_message.py", line 450, in deserialize
return super().deserialize(value, **kwargs)
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/messaging/models/base.py", line 205, in deserialize
raise BaseModelError(f"{cls.__name__} schema validation failed") from err
aries_cloudagent.messaging.models.base.BaseModelError: ConnectionInvitation schema validation failed
2023-05-26 20:28:51,719 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/messaging/models/base.py", line 201, in deserialize
schema.loads(obj) if isinstance(obj, str) else schema.load(obj),
File "/home/indy/.venv/lib/python3.6/site-packages/marshmallow/schema.py", line 723, in load
data, many=many, partial=partial, unknown=unknown, postprocess=True
File "/home/indy/.venv/lib/python3.6/site-packages/marshmallow/schema.py", line 904, in _do_load
raise exc
marshmallow.exceptions.ValidationError: {'imageUrl': ['Not a valid URL.']}
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/indy/.venv/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
resp = await request_handler(request)
File "/home/indy/.venv/lib/python3.6/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/home/indy/.venv/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 171, in ready_middleware
return await handler(request)
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 208, in debug_middleware
return await handler(request)
File "/home/indy/.venv/lib/python3.6/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware
return await handler(request)
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 328, in check_token
return await handler(request)
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 376, in check_multitenant_authorization
return await handler(request)
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/admin/server.py", line 420, in setup_context
return await task
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 250, in _wakeup
future.result()
File "/home/indy/.pyenv/versions/3.6.13/lib/python3.6/asyncio/tasks.py", line 180, in _step
result = coro.send(None)
File "/home/indy/traction_plugins/traction_innkeeper/v1_0/connections/routes.py", line 38, in connections_invitation
invitation = await connection.retrieve_invitation(session)
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/connections/models/conn_record.py", line 442, in retrieve_invitation
).deserialize(ser)
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/messaging/agent_message.py", line 450, in deserialize
return super().deserialize(value, **kwargs)
File "/home/indy/.venv/lib/python3.6/site-packages/aries_cloudagent/messaging/models/base.py", line 205, in deserialize
raise BaseModelError(f"{cls.__name__} schema validation failed") from err
aries_cloudagent.messaging.models.base.BaseModelError: ConnectionInvitation schema validation failed
```

Putting a validly formed URL in there seems to stop the issue.

Investigate:

-  Is this a problem with the invitation creation? Known issue in ACA-Py?
-  Check if BC Wallet team knows about the behaviour maybe
-  We can solve this with some validation on the Tenant UI frontend but is there something deeper that needs to be fixed? (you can update a wallet without Tenant UI)

**Comment by loneil** [comment]
Step 1: Validate this on the Tenant UI at least.
https://github.com/bcgov/traction/pull/642 does that

**Comment by loneil** [comment]
Created 
https://github.com/bcgov/traction/issues/641 to mitigate this in Traction

FYI @esune 

And brought up the core ACA-Py functionality for Image URL in this ticket
https://github.com/hyperledger/aries-cloudagent-python/issues/2254
