### ISSUE TITLE
Error on Reservation list

### ISSUE THREAD

**Issue by loneil** [bcgov/traction#815]
Investigation into 500 error currently occurring in main branch code (deployed in Traction DEV env)

- Innkeeper Reservation (or Reservation History) page through tenant UI
- Also can just call API `/innkeeper/reservations` (https://traction-tenant-proxy-dev.apps.silver.devops.gov.bc.ca/api/doc#/traction-innkeeper/get_innkeeper_reservations_)
- Happens if existing older reservations with any of the fields removed from the Reservation model have existing data in them.

Happing on this line
`super().__init__(reservation_id, state or self.STATE_REQUESTED, **kwargs)`
in `plugins\traction_innkeeper\traction_innkeeper\v1_0\innkeeper\models.py` in the **ReservationRecord** class
Occurs on first fetch of a record with fields that do not play nice as the kwargs going to the init method.

Example (added this log statement locally printing kwargs). See full error at bottom
`traction_plugins.traction_innkeeper.v1_0.innkeeper.models INFO kwargs = {'created_at': '2023-09-11T16:25:03.031379Z', 'updated_at': '2023-09-11T16:25:05.481179Z', 'tenant_reason': '123', 'contact_name': "Lucas O'Neil", 'contact_phone': '112'}`
then fails as `__init__` can't handle tenant_reason as a kwarg.

Ideas?
- Datafix that data out of older records? (ideally put in new context_data fields)
- Revert changes?
- Just add in tenant_reason, contact_name, contact_phone, _back_ in the model __init__ ? Until sorted later maybe?

```
2023-09-14 23:40:19,029 aiohttp.server ERROR Error handling request
Traceback (most recent call last):
  File "/home/aries/.venv/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "/home/aries/.venv/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/home/aries/.venv/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 181, in ready_middleware       
    return await handler(request)
  File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 218, in debug_middleware       
    return await handler(request)
  File "/home/aries/.venv/lib/python3.9/site-packages/aiohttp_apispec/middlewares.py", line 45, in validation_middleware     
    return await handler(request)
  File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 338, in check_token
    return await handler(request)
  File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 387, in check_multitenant_authorization
    return await handler(request)
  File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/admin/server.py", line 450, in setup_context
    return await task
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step
    result = coro.send(None)
  File "/home/aries/traction_plugins/traction_innkeeper/v1_0/innkeeper/routes.py", line 55, in wrapper
    ret = await func(request)
  File "/home/aries/traction_plugins/traction_innkeeper/v1_0/innkeeper/routes.py", line 88, in wrapper
    raise err
  File "/home/aries/traction_plugins/traction_innkeeper/v1_0/innkeeper/routes.py", line 72, in wrapper
    ret = await func(request)
  File "/home/aries/traction_plugins/traction_innkeeper/v1_0/innkeeper/routes.py", line 548, in innkeeper_reservations_list  
    records = await ReservationRecord.query(
  File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/messaging/models/base_record.py", line 331, in query  
    result.append(cls.from_storage(record.id, vals))
  File "/home/aries/.venv/lib/python3.9/site-packages/aries_cloudagent/messaging/models/base_record.py", line 120, in from_storage
    return cls(**params)
  File "/home/aries/traction_plugins/traction_innkeeper/v1_0/innkeeper/models.py", line 73, in __init__
    super().__init__(reservation_id, state or self.STATE_REQUESTED, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'tenant_reason'
```

**Comment by loneil** [comment]
Basically Sherman's comment here
https://github.com/bcgov/traction/issues/810

> dropping fields can be an issue. If any data gets left behind, it will blow up when it attempts to marshal itself out of the record.

**Comment by loneil** [comment]
Also was confused for a while when looking for any reference to `tenant_reason` that it was found here
![image](https://github.com/bcgov/traction/assets/17445138/3e3a67fe-bc1f-42cc-a228-b4710b00c19c)
also in `models/py`

Even though the field names appear to be stored named differently?
![image](https://github.com/bcgov/traction/assets/17445138/875a8760-fd68-49f2-bb2f-4fdb86ae82e5)

Don't think this affects this issue? Just a swagger documentation typo?
