### ISSUE TITLE
Issues when starting devcontainer

### ISSUE THREAD

**Issue by esune** [bcgov/traction#876]
When starting the devcontainer set-up for Traction, the agent seems to be unable to start-up correctly due to an (apparent) issue with conencting to the database:

```
2023-10-17 01:29:33,591 aries_cloudagent.commands.start ERROR Exception during startup:
Traceback (most recent call last):
  File "/workspaces/traction/plugins/.venv/lib/python3.9/site-packages/aries_cloudagent/askar/store.py", line 157, in open_store
    store = await Store.open(
  File "/workspaces/traction/plugins/.venv/lib/python3.9/site-packages/aries_askar/store.py", line 326, in open
    return Store(await bindings.store_open(uri, key_method, pass_key, profile), uri)
  File "/workspaces/traction/plugins/.venv/lib/python3.9/site-packages/aries_askar/bindings/__init__.py", line 83, in store_open
    return await invoke_async(
  File "/workspaces/traction/plugins/.venv/lib/python3.9/site-packages/aries_askar/bindings/lib.py", line 358, in invoke_async
    return await self.loaded.invoke_async(
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 328, in __wakeup
    future.result()
  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result
    raise self._exception
aries_askar.error.AskarError: Backend error
Caused by: pool timed out while waiting for an open connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/traction/plugins/.venv/lib/python3.9/site-packages/aries_cloudagent/commands/start.py", line 72, in init
    await startup
  File "/workspaces/traction/plugins/.venv/lib/python3.9/site-packages/aries_cloudagent/commands/start.py", line 28, in start_app
    await conductor.setup()
  File "/workspaces/traction/plugins/.venv/lib/python3.9/site-packages/aries_cloudagent/core/conductor.py", line 135, in setup
    self.root_profile, self.setup_public_did = await wallet_config(context)
  File "/workspaces/traction/plugins/.venv/lib/python3.9/site-packages/aries_cloudagent/config/wallet.py", line 54, in wallet_config
    profile = await mgr.open(context, profile_cfg)
  File "/workspaces/traction/plugins/.venv/lib/python3.9/site-packages/aries_cloudagent/askar/profile.py", line 298, in open
    opened = await store_config.open_store(provision=False)
  File "/workspaces/traction/plugins/.venv/lib/python3.9/site-packages/aries_cloudagent/askar/store.py", line 171, in open_store
    raise ProfileError("Error opening store") from err
aries_cloudagent.core.error.ProfileError: Error opening store

Shutting down
```

**Comment by gurjmatharu** [comment]
- we can close this.  Turns out it was a wsl relay issue.  Killing the process resolved this for me.  
See: https://github.com/microsoft/WSL/issues/10601

**Comment by esune** [comment]
Moving to blocked while we wait to be able to test a resolution.
